apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-build
spec:
  resources:
  steps:
    - name: cross-build
      image: quay.io/mayurwaghmode111/buildah-with-podman
      script: |
        #!/usr/bin/env bash
        podman run --rm --privileged docker.io/multiarch/qemu-user-static --reset -p yes
        cat > Dockerfile << EOF
        FROM docker.io/ppc64le/ubuntu:20.04
        RUN apt-get update -y
        ENTRYPOINT ["/bin/cat","/proc/cpuinfo"]
        EOF
        buildah bud -f Dockerfile -t ppc64le .
        buildah from localhost/ppc64le
        buildah commit ppc64le-working-container ppc64lecntwithincnt
        buildah login -u mwaghmodepersistent -p Mpersistentchess@123 docker.io
        buildah push ppc64lecntwithincnt mwaghmodepersistent/ppc64lecntwithincnt
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
  volumes:
    - name: varlibcontainers
      emptyDir: {}
