apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-docker-image-from-git-source-pipeline-run
spec:
  serviceAccountName: dockerhub-service
  pipelineRef:
    name: build-docker-image-from-git-source-pipeline
  params:
    - name: pathToDockerFile
      value: Dockerfile
  resources:
    - name: docker-source
      resourceRef:
        name: ubuntugit
    - name: builtImage
      resourceRef:
        name: ubuntuimage
    - name: buildahImage
      resourceRef:
        name: buildahimage
    - name: builtCntImage
      resourceRef:
        name: builtcntimage
