apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: buildahimage
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: quay.io/buildah/stable
